package Model;

public enum Commands {
    LOGIN_REQUEST,
    REGISTRATION_REQUEST,
    ADD_TO_CONTACTS_REQUEST,
    CHAT_REQUEST,
    SEND_MESSAGE_REQUEST,
    LOGOUT_REQUEST,
    CLOSE_CHAT_VIEW_REQUEST,

    LOGIN_SUCCESSFUL,
    LOGIN_UNSUCCESSFUL,
    REGISTRATION_SUCCESSFUL,
    REGISTRATION_UNSUCCESSFUL,
    CONNECTED_USER,
    START_CHATTING,
    SHOW_MESSAGE,
    SHOW_CONTACTS,
    REMOVE_ACTIVE_USER,
    SHOW_STORED_MESSAGES,
    CLOSE_CHAT_VIEW

}
